
tasks:
  - name: "init scoreboard env"
    init: |
      nvm install v23.3.0
      git checkout $(git describe --tags --abbrev=0)
      npm install
      chmod -R 755 node_modules/
    command: npm start
